version: "2.2"
services:
  django:
    build: .
    image: rogerhuauya/bude-semantic-search-django:django
    container_name: bude_server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true
  vite:
    build:
      context: ./web-app
    image: rogerhuauya/bude-semantic-search-vite:django
    user: root
    container_name: web_vite_dev
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./web-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
