version: "2.2"
services:
  django:
    build: .
    container_name: bude_server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true
  db:
    container_name: bude_db_dev
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
  vite:
    build:
      context: ./web-app
    user: root
    container_name: web_vite_dev
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./web-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  postgres-data: