# Generated by Django 5.0.2 on 2024-07-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
