# Generated by Django 5.0.2 on 2024-07-10 19:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_pgvector_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=360, null=True),
        ),
    ]
