# Generated by Django 5.0.2 on 2024-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverted_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file', models.FileField(upload_to='blocks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
