# Generated by Django 5.0.2 on 2024-07-13 23:32

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_file', models.FileField(upload_to='image_files/')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=360, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('master_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('article_type', models.CharField(blank=True, max_length=100, null=True)),
                ('base_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('product_display_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
