# Generated by Django 5.0.2 on 2024-07-14 00:24

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='image_embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
